initial Steps commit
learnhubmk/skopje-paws pull request #18
Opened 2024-06-24 18:30 UTC by Mario-k4

#4

2024-06-26 10:00 UTC, RevanchistX requested changes
The overall look and feel is ok, just need some technical improvements for consistency.

2024-06-26 10:00 UTC, RevanchistX commented on components/Steps/StepsCard.tsx
> +        <div className={`w-80 h-80 sm:w-80 sm:h-80 xl:w-80 xl:h-80 lg:w-56 lg:h-56 sm:w-40 sm:h-40 rounded-4xl bg-${color} p-5 sm:p-7 lg:px-6 lg:py-5`}>
You have multiple sm declarations for height and width - sm:w-80, sm:h-80, sm:w-40, sm:h-40.

2024-06-26 10:00 UTC, RevanchistX commented on components/Steps/StepsCard.tsx
> +    image?: React.ReactNode;
It's not a good idea to assign images like this, since React.ReactNode can technically be any type of element.

2024-06-26 10:00 UTC, RevanchistX commented on tailwind.config.ts
> +import type { Config } from "tailwindcss";
Unnecessary change.

2024-06-26 10:00 UTC, RevanchistX commented on components/Steps/StepsCard.tsx
> +        <div className={`w-80 h-80 sm:w-80 sm:h-80 xl:w-80 xl:h-80 lg:w-56 lg:h-56 sm:w-40 sm:h-40 rounded-4xl bg-${color} p-5 sm:p-7 lg:px-6 lg:py-5`}>
Additionally, on small screens, the padding on the right is inconsistent
![image](https://github.com/learnhubmk/skopje-paws/assets/11035261/370af8b2-5125-4f1e-b74c-9387d8e84072)

2024-06-26 10:00 UTC, RevanchistX commented on components/Steps/StepsCard.tsx
> +        <div className={`w-80 h-80 sm:w-80 sm:h-80 xl:w-80 xl:h-80 lg:w-56 lg:h-56 sm:w-40 sm:h-40 rounded-4xl bg-${color} p-5 sm:p-7 lg:px-6 lg:py-5`}>
``bg-${color}`` only works in this scenario because ``bg-cream`` / ``bg-orange`` already exist elsewhere in the project.
If you try this with any other color that is defined in ``tailwind.config.js``, you would not be able to compile it.
This is because tailwind only scans for classes that already exist in the project, so dynamic classes cannot be used without making workarounds.

The better approach would be to pass ``bg-cream`` as a value for the ``color`` property, and then just render `${color}`, since that way it guarantees that the value will show up when tailwind scans the project.

2024-06-26 10:55 UTC, Mario-k4 commented on tailwind.config.ts
> +import type { Config } from "tailwindcss";
Auto format :D

2024-06-26 16:01 UTC, Mario-k4 commented on components/Steps/StepsCard.tsx
> +        <div className={`w-80 h-80 sm:w-80 sm:h-80 xl:w-80 xl:h-80 lg:w-56 lg:h-56 sm:w-40 sm:h-40 rounded-4xl bg-${color} p-5 sm:p-7 lg:px-6 lg:py-5`}>
Not sure if i used the right approach for the background color,will fix it after feedback if its not correct.

2024-06-27 10:32 UTC, RevanchistX approved these changes
LGTM

2024-06-27 10:36 UTC, merged