Create Footer
learnhubmk/skopje-paws pull request #20
Opened 2024-06-27 19:50 UTC by maznevskia

2024-06-27 22:08 UTC, RevanchistX requested changes
Overall look and feel is ok.
Needs refactoring, since every class used is a custom tailwind class.
Needs responsive design.

2024-06-27 22:08 UTC, RevanchistX commented on components/Footer.tsx
> +            <div className="flex flex-col items-center relative border-2 rounded-[25px] border-[#FFAC66] w-[1240px] h-[281px]">
do not use custom tailwind values when there are provided values that accomplish the same
refer to this for easier management of values
https://nerdcave.com/tailwind-cheat-sheet

2024-06-27 22:08 UTC, RevanchistX commented on components/Footer.tsx
> +import img from "../public/footerLogo.svg";
use descriptive variable names

2024-06-27 22:08 UTC, RevanchistX commented on components/Footer.tsx
> +                <Image src={paws} alt={"Paws 1"} width={78.74} height={78.74} className="absolute top-[113px] left-[81px] rotate-[-157deg]"></Image>
Image is a self-closing tag, so </Image> is unnecessary. 
Additionally when sourcing statically imported images, there's no need to provide width/height values.

2024-06-27 22:08 UTC, RevanchistX commented on components/Footer.tsx
> +            <div className="flex flex-col items-center relative border-2 rounded-[25px] border-[#FFAC66] w-[1240px] h-[281px]">
Additionally, you can add missing colors to `tailwind.config.js` and reference them normally.

2024-06-28 19:13 UTC, RevanchistX requested changes
LGTM, just need few minor modifications

2024-06-28 19:13 UTC, RevanchistX commented on components/Footer.tsx
> +                    <a className="text-lg md:text-xl lg:text-2xl text-black mb-6" href="tel:077805229">077 805 229</a>
The element is not clickable. Try adding `z-10` to bring the element to the foreground.

2024-06-28 19:13 UTC, RevanchistX commented on components/Footer.tsx
> +                <Image src={footerLogo} alt="Hero Image" className="mx-auto w-16 h-16 md:w-20 md:h-20 lg:w-24 lg:h-24 mb-4" />
This is not a Hero image, change the text to something more consistent.

2024-06-28 19:13 UTC, RevanchistX commented on components/Footer.tsx
> +                    <a className="text-lg md:text-xl lg:text-2xl text-black mb-6" href="tel:077805229">077 805 229</a>
Additionally, the `href` value should probably be prefixed with +38977...  for consistency, as I don't think it would be usable otherwise. (I might be wrong on this, but better safe than sorry).
You can leave the display value the same.

2024-06-28 19:13 UTC, RevanchistX commented on components/Footer.tsx
> +                        <a href="https://www.linkedin.com/company/skopje-paws/" target="_blank" className="w-32 h-10 border-2 border-orange flex items-center justify-center rounded-md rotate-[-1deg]
This looks good on the responsive design, but kinda empty on the full design.

Good:
![image](https://github.com/learnhubmk/skopje-paws/assets/11035261/e6dff9a1-5e92-4e2a-9cdc-bec88c95d0e9)

Needs improvement -  Maybe adjust the button to match the same look and feel as the previous image, so there's more visual consistency and less empty space.
![image](https://github.com/learnhubmk/skopje-paws/assets/11035261/e49e64bc-9ddf-4a34-913c-5d26354eb304)


The rest look fine.

2024-06-29 12:44 UTC, RevanchistX requested changes
LGTM

2024-06-29 12:45 UTC, RevanchistX submitted a review, later dismissed
LGTM

2024-07-01 18:27 UTC, RevanchistX approved these changes, later dismissed

2024-07-01 18:28 UTC, RevanchistX approved these changes

2024-07-01 18:28 UTC, RevanchistX approved these changes
LGTM

2024-07-01 18:30 UTC, davorminchorov approved these changes

2024-07-01 18:30 UTC, merged