FAQ section
learnhubmk/skopje-paws pull request #21
Opened 2024-06-28 21:49 UTC by DanielK-12

2024-06-29 12:36 UTC, RevanchistX requested changes
The general look and feel of the component doesn't match the provided design.
The design should look like this:
![image](https://github.com/learnhubmk/skopje-paws/assets/11035261/00a2d5fc-2d31-429d-beb8-08c8a5a16b37)

The implementation currently looks like this.
![image](https://github.com/learnhubmk/skopje-paws/assets/11035261/5794b709-3bae-4b9c-bb22-6995f75f7640)

Additionally, make sure to implement responsive design where applicable.
![image](https://github.com/learnhubmk/skopje-paws/assets/11035261/561fed03-dd78-4ca3-90df-8078bda52796)

2024-06-29 12:36 UTC, RevanchistX commented on components/FAQ/FAQAccordion.tsx
> +      <div style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
Unnecessary style declaration, you can use tailwind classes for this.

2024-06-29 12:36 UTC, RevanchistX commented on components/FAQ/FAQAccordion.tsx
> +export default function FAQDropDown() {
Function name should match file name.

2024-06-29 12:36 UTC, RevanchistX commented on components/FAQ/FAQAccordion.tsx
> +        <h2>Често поставувани
Implementation doesn't match the design. Text should be bold and larger in size.

2024-06-29 12:36 UTC, RevanchistX commented on components/LinkButton.tsx
> +const LinkButton = ({ type, url, text, callback, bgColor, textColor }: LinkButtonProps) => {
Unnecessary changes.

2024-06-29 12:36 UTC, RevanchistX commented on components/FAQ/FAQAccordion.tsx
> +        <LinkButton type={'link'} url={''} text={'Поставете прашање'} bgColor={'bg-orange'} textColor={'text-black'}></LinkButton>
Button should not be the full width of the parent.

2024-06-29 12:36 UTC, RevanchistX commented on components/FAQ/FAQAccordion.tsx
> +        <details className="group [&_summary::-webkit-details-marker]:hidden">
I've never seen anything like this before. What does it do?

2024-06-29 12:36 UTC, RevanchistX commented on components/FAQ/FAQAccordion.tsx
> +            className="flex cursor-pointer items-center justify-between gap-1.5 rounded-lg bg-gray-50 p-4 text-black-900" style={{ border: '1px solid #FFAC66' }}
Unnecessary style declaration. Border doesn't look like in design.

2024-06-29 12:36 UTC, RevanchistX commented on components/FAQ/FAQAccordion.tsx
> +          <p className="mt-4 px-4 leading-relaxed text-gray-700" style={{ border: '1px solid #FFAC66', background: '#FFAC66' }}>
Doesn't look like the design. The orange part should be part of the dropdown.
Opening the dropdown also affects the left side of the component -  the left side of the component shouldn't change size.

![image](https://github.com/learnhubmk/skopje-paws/assets/11035261/b1dc40a8-cbb2-432b-b2eb-433ff565946d)

2024-06-29 12:36 UTC, RevanchistX commented on components/FAQ/FAQAccordion.tsx
> +            className="flex cursor-pointer items-center justify-between gap-1.5 rounded-lg bg-gray-50 p-4 text-black-900" style={{ border: '1px solid #FFAC66' }}
Should use different font than the default one.

2024-06-29 12:36 UTC, RevanchistX commented on components/FAQ/FAQAccordion.tsx
> +        <details className="group [&_summary::-webkit-details-marker]:hidden">
When creating iterative/dynamic content like this, it's better to isolate the data in a separate (JSON) file, and iterate over it. This will help you prevent multiple declarations of the same segment that can go out of sync very quick if you are not paying attention.

For example, the JSON file should look like this:

```
[
{question: "Bla bla?", answer: "Bla bla bla!"},
{question: "Bla bla 1?", answer: "Bla bla bla 1!"}
]
```

2024-07-17 07:59 UTC, RevanchistX requested changes
You changed the component from summary/detail based to pure divs. 
Overall look/feel/functionality is fine. Just finish up the changes.

2024-07-17 07:59 UTC, RevanchistX commented on components/FAQ/FAQ.tsx
> +const montserrat = Montserrat({ subsets: ['cyrillic'], weight: ['400', '500', '700'] });
The font should be loaded in the layout. 

https://nextjs.org/docs/app/building-your-application/optimizing/fonts#with-tailwind-css

2024-07-17 07:59 UTC, RevanchistX commented on components/FAQ/FAQ.tsx
> +        <LinkButton type={'link'} url={''} text={'Поставете прашање'} bgColor={'bg-orange'} textColor={'text-black'}></LinkButton>
Don't use LinkButton, it's a dummy component that should be deleted.

2024-07-17 07:59 UTC, RevanchistX commented on components/FAQ/FAQ.tsx
> +          <div className="flex grow size-full items-center justify-between" onClick={() => {
You shouldn't do inline callbacks. It makes the code more difficult to read. Instead make a callback before `return` and then use it here.

https://stackoverflow.com/questions/73615347/passing-a-parameter-to-onclick-function-nextjs

2024-07-17 07:59 UTC, RevanchistX commented on components/FAQ/FAQAccordion.tsx
> +const montserrat = Montserrat({ subsets: ['cyrillic'], weight: ['400', '500', '700'] });
Duplicate font declaration.

2024-07-17 07:59 UTC, RevanchistX commented on components/FAQ/FAQAccordion.tsx
Needs improvement for small screens.
![image](https://github.com/user-attachments/assets/4a4289f0-dae2-4244-9dca-289d888a2343)

2024-07-31 08:00 UTC, RevanchistX approved these changes, later dismissed
LGTM

2024-09-02 21:17 UTC, maznevskia commented
The conflicts were in Layout, which would have affected all components, I made the changes only for FAQ and resolved the other conflicts.

2024-09-29 10:38 UTC, RevanchistX approved these changes
LGTM

2024-09-30 17:52 UTC, merged