#9-Blog-listing
learnhubmk/skopje-paws pull request #22
Opened 2024-07-01 19:51 UTC by aleksandarmicev

2024-07-02 10:30 UTC, RevanchistX requested changes

2024-07-02 10:30 UTC, RevanchistX commented on tailwind.config.js
This file is unnecessary.

2024-07-02 10:30 UTC, RevanchistX commented on components/Navigation.tsx
These changes have nothing to do with the scope of the task.

2024-07-02 10:30 UTC, RevanchistX commented on components/Gallery.tsx
These changes have nothing to do with the scope of the task.

2024-07-02 10:30 UTC, RevanchistX commented on app/page.tsx
Too many changes for just adding a new component to the page.

2024-07-02 10:30 UTC, RevanchistX commented on components/BlogCard/BlogCard.tsx
> +          <div className="font-bold text-xl text-gray-900">{title}</div>
`text-gray-900` is not defined in tailwind.

2024-07-02 10:30 UTC, RevanchistX commented on components/BlogCard/blog.tsx
> +const blogs = [
Blog data should be in a separate file

2024-07-02 10:30 UTC, RevanchistX commented on components/BlogCard/blog.tsx
> +    time: "26.6.2024",
variable name should be `date`

2024-07-04 14:26 UTC, aleksandarmicev commented on components/Navigation.tsx
Actually, this is only Prettier, it's not changes of the lines of code

2024-07-04 14:26 UTC, aleksandarmicev commented on app/page.tsx
Actually, this is only Prettier, it's not changes of the lines of code

2024-07-04 15:01 UTC, RevanchistX commented on components/Navigation.tsx
That's not possible since Prettier is not configured for this project.
Additionally, even if it was, you shouldn't change components that do not affect the scope of the task.

2024-07-04 15:03 UTC, RevanchistX commented on app/page.tsx
Like I mentioned in the other comment, Prettier is not defined for the project, so that's not true.
Even if it was, you shouldn't leave code like this and hope that some automated system fixes your mistakes.
![image](https://github.com/learnhubmk/skopje-paws/assets/11035261/3ee77c74-e358-4b51-ad01-682f8c2414c6)

2024-07-04 15:05 UTC, RevanchistX commented on components/BlogCard/blog.tsx
> +    time: "26.6.2024",
While you changed the BlogCardProps, you forgot to change the variables in the data.

2024-07-04 15:06 UTC, RevanchistX commented on components/BlogCard/BlogCard.tsx
> +          <div className="text-gray-500 text-sm">{time}</div>
`text-gray-500` is not defined in tailwind.

2024-07-04 15:06 UTC, RevanchistX commented on components/BlogCard/BlogCard.tsx
> +        <p className="text-gray-700 text-base">{text}</p>
`text-gray-700` is not defined in tailwind.

2024-07-04 15:13 UTC, RevanchistX commented on components/BlogCard/blog.tsx
> +            date={blog.time}
`blog.time` should be `blog.date` for consistency.
If you want to ensure that the blogs are typed correctly, you can export the `BlogCardProps` interface and use it for the blog variable to ensure consistency. That's one of the main benefits of TypeScript.
example:
```
 {blogs.map((blog: BlogCardProps, index) => ( 
 ```

2024-07-08 17:51 UTC, RevanchistX approved these changes

2024-07-09 11:00 UTC, merged